feat: improve logic in the starbook
gogf/gf-doc pull request #135
Opened 2024-12-22 09:46 UTC by oldme-git

2024-12-23 01:22 UTC, gqcn requested changes

2024-12-23 01:22 UTC, gqcn commented on docs/course/starbook/第二章-用户注册/2.3.注册接口.md
> +    usersL "star/internal/logic/users"
在API中，接口包名应该是`v1/v2`这样的形式，而在`logic`中，应该是`users`这样的形式，因此并不需要设置别名。

2024-12-23 01:22 UTC, gqcn commented on docs/course/starbook/第二章-用户注册/2.3.注册接口.md
> +       users: &usersL.Users{},
最好通过`New`的创建方法来初始化业务逻辑封装对象，因为外部调用时并不知道一个逻辑对象需要做什么初始化逻辑。直接使用`&usersL.Users{}`的方式就无法进行初始化逻辑封装了。

2024-12-23 01:22 UTC, gqcn commented on docs/course/starbook/第四章-单词管理/4.3.新增单词.md
> +       words: &wordsL.Words{},
同上。

2024-12-23 01:22 UTC, gqcn commented on docs/course/starbook/第三章-会话管理/3.2.登录.md
> +type userClaims struct {
这个结构体为什么不公开呢？

2024-12-23 01:25 UTC, oldme-git commented on docs/course/starbook/第二章-用户注册/2.3.注册接口.md
> +    usersL "star/internal/logic/users"
`users`包名被`star/api/users`占用了

2024-12-23 01:25 UTC, oldme-git commented on docs/course/starbook/第三章-会话管理/3.2.登录.md
> +type userClaims struct {
这个结构体`users`内部用的，想着也没必要公开

2024-12-23 01:31 UTC, oldme-git commented on docs/course/starbook/第二章-用户注册/2.3.注册接口.md
> +    usersL "star/internal/logic/users"
`users`被`"star/api/users"`占用了，那个是`gen ctrl`生成的

2025-01-02 12:50 UTC, gqcn approved these changes

2025-01-02 12:50 UTC, merged