style: 文档矫正
gogf/gf-doc pull request #31
Opened 2024-11-06 09:33 UTC by oldme-git

2024-11-06 12:25 UTC, gqcn requested changes

2024-11-06 12:25 UTC, gqcn commented on docs/docs/框架设计/工程开发设计/工程目录设计.md
> +| &nbsp;&nbsp;&nbsp;&nbsp;`- protobuf`                       | 协议文件 | `GRPC` 协议时使用的 `protobuf` 协议定义文件，协议文件编译后生成 `go` 文件到 `api` 目录。   |
感觉不太需要使用`&nbsp;`来替换`符号中的空格

2024-11-07 01:45 UTC, oldme-git commented on docs/docs/框架设计/工程开发设计/工程目录设计.md
> +| &nbsp;&nbsp;&nbsp;&nbsp;`- protobuf`                       | 协议文件 | `GRPC` 协议时使用的 `protobuf` 协议定义文件，协议文件编译后生成 `go` 文件到 `api` 目录。   |
Done

2024-11-10 06:25 UTC, gqcn approved these changes

2024-11-10 06:25 UTC, merged